name: CI
on: [push,pull_request]
jobs:
  lint:
    name: Golangci-lint
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
      
  test:
    name: Unit Testing
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Checkout
      uses: actions/checkout@v2
    - name: Go Test
      run: go test -v ./...
