name: CI
on: [push,pull_request]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      
  test:
    #needs: Lint
    name: Unit Testing
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Checkout
      uses: actions/checkout@v2
    - name: Go Test
      run: go test -v ./...
